// THIS FILE IS AUTOMATICALLY GENERATED BY HIVE. DO NOT EDIT THIS FILE.
part of 'maintenance_record.dart';

class MaintenanceRecordAdapter extends TypeAdapter<MaintenanceRecord> {
  @override
  final int typeId = 0;

  @override
  MaintenanceRecord read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (int i = 0; i < numOfFields; i++) {
      final key = reader.readByte();
      switch (key) {
        case 0:
          fields[0] = reader.readString();
          break;
        case 1:
          fields[1] = reader.readString();
          break;
        case 2:
          fields[2] = reader.readString();
          break;
        case 3:
          fields[3] = reader.readString();
          break;
        case 4:
          fields[4] = reader.readString();
          break;
        case 5:
          fields[5] = reader.readString();
          break;
      }
    }

    return MaintenanceRecord(
      date: fields[0] as String,
      machine: fields[1] as String,
      issue: fields[2] as String,
      technician: fields[3] as String,
      action: fields[4] as String,
      notes: fields[5] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, MaintenanceRecord obj) {
    writer.writeByte(6);
    writer.writeByte(0);
    writer.writeString(obj.date);
    writer.writeByte(1);
    writer.writeString(obj.machine);
    writer.writeByte(2);
    writer.writeString(obj.issue);
    writer.writeByte(3);
    writer.writeString(obj.technician);
    writer.writeByte(4);
    writer.writeString(obj.action);
    writer.writeByte(5);
    writer.writeString(obj.notes ?? '');
  }

  @override
  int get hashCode => typeId;

  @override
  bool operator ==(Object other) =>
      other is MaintenanceRecordAdapter && other.typeId == typeId;
}
